services:
  authority:
    build: ./authority-node
    ports:
      - "4000:4000"
    networks:
      - blockchain
    healthcheck:
      # Wait for BOTH endpoints to respond 200 OK
      test: ["CMD-SHELL", "wget -q -O- http://localhost:4000/merkleRoot >/dev/null && wget -q -O- http://localhost:4000/hePublicKey >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 20        # allow time for keygen
      start_period: 30s  # Paillier keygen can take seconds

  zk-service:
      build: ./zk-service
      env_file: ./election.env
      ports:
        - "5000:5000"
      networks:
        - blockchain
      depends_on:
        authority:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
        interval: 5s
        timeout: 3s
        retries: 5
        start_period: 10s
  
  node1:
    build: ./blockchain
    ports:
      - "3001:3001"
      - "6001:6001"
    env_file: ./election.env
    environment:
      - NODE_ID=3001
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=ws://node2:6001,ws://node3:6001
    depends_on:
      authority:
        condition: service_healthy
    networks:
      - blockchain

  node2:
    build: ./blockchain
    ports:
      - "3002:3001"
      - "6002:6001"
    env_file: ./election.env
    environment:
      - NODE_ID=3002
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=ws://node1:6001,ws://node3:6001
    depends_on:
      authority:
        condition: service_healthy
    networks:
      - blockchain

  node3:
    build: ./blockchain
    ports:
      - "3003:3001"
      - "6003:6001"
    env_file: ./election.env
    environment:
      - NODE_ID=3003
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=ws://node1:6001,ws://node2:6001
    depends_on:
      authority:
        condition: service_healthy
    networks:
      - blockchain

networks:
  blockchain:
    driver: bridge
