services:
  authority:
    build: ./authority-node
    ports:
      - "4000:4000"
    networks:
      - blockchain

  node1:
    build: ./blockchain
    ports:
      - "3001:3001"
      - "6001:6001"
    environment:
      - NODE_ID=3001
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=ws://node2:6001,ws://node3:6001
    networks:
      - blockchain

  node2:
    build: ./blockchain
    ports:
      - "3002:3001"
      - "6002:6001"
    environment:
      - NODE_ID=3002
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=ws://node1:6001,ws://node3:6001
    networks:
      - blockchain

  node3:
    build: ./blockchain
    ports:
      - "3003:3001"
      - "6003:6001"
    environment:
      - NODE_ID=3003
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=ws://node1:6001,ws://node2:6001
    networks:
      - blockchain

networks:
  blockchain:
    driver: bridge
